package objects;

public enum ObjectType {
	ENTITY, ENTITYSTATIC, PLAYER, BOSS, LIFE, PIPE,ENERGYDRINK, OBSTACLE, TIMEDOBSTACLE, BULLET, QUESTTRIGGER, BLOCKTRIGGER, TELEPORTTRIGGER, UNDEFINED;
}
